"""Short, user-facing explanations for non-DSP controls."""

TIPS = {
    'status_pill': 'LIVE means game chat is connected. NO LINK means it is unavailable. MUTED means voice output is off.',
    'btn_back': 'Show received messages.',
    'btn_settings_nav': 'Choose voices and audio settings.',
    'btn_adv_back': 'Adjust radio settings.',
    'btn_adv': 'Adjust the radio sound in more detail.',
    'btn_reset_all': 'Restore voices, speed, engine and radio settings to their defaults.',
    'btn_restart': 'Restart the app while keeping your settings.',
    'btn_cloud': 'Use online neural voices for ally and enemy messages.',
    'btn_offline': 'Use separate downloaded voices for ally and enemy messages.',
    'cb_ally': 'Choose the voice used for allied messages.',
    'cb_enemy': 'Choose the voice used for enemy messages.',
    'cb_piper': 'Choose an offline voice for this side. Download it below if needed.',
    'local_dl_btn': 'Download the selected offline voice. Progress is shown below.',
    'btn_speed_lo': 'Read messages more slowly.',
    'btn_speed_hi': 'Read messages more quickly.',
    'btn_fx_master': 'Turn radio sound effects on or off.',
    'btn_fx_ptt': 'Add a push-to-talk click and squelch at the start and end of messages.',
    'btn_fx_eq': 'Give voices a narrower, compressed radio sound.',
    'btn_fx_sync': 'Play the optional sync tone before a transmission.',
    'btn_adv_speaker': 'Give playback a small-speaker sound.',
    'mute_default_messages': 'Do not speak common built-in radio messages such as “Awesome!” or repeated attack orders. They remain visible in COMMS.',
    'noise_scale': 'Adjust how much radio static accompanies messages.',
    'volume_main_scale': 'Adjust the loudness of all spoken messages. 1.00 is normal.',
    'btn_mute': 'Mute or unmute spoken messages. Received text remains visible.',
    'cb_profile': 'Choose a radio sound preset. Adjusting an effect makes it a custom profile.',
    'cb_codec': 'CVSD adds a gritty radio sound. NONE keeps the voice clear.',
}
